#!/usr/bin/env bash
#
# One-shot installer for the file server.
#   ./install.sh
#
# Generates secrets, prompts for credentials, builds the image, starts the
# container. Re-runnable: keeps your existing .env if present.
#
set -euo pipefail

#-----------------------------------------------------------
# pretty output
#-----------------------------------------------------------
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
log()    { printf "${GREEN}[+]${NC} %s\n" "$*"; }
warn()   { printf "${YELLOW}[!]${NC} %s\n" "$*"; }
err()    { printf "${RED}[✗]${NC} %s\n" "$*" >&2; }
prompt() { printf "${BLUE}[?]${NC} %s" "$*"; }

#-----------------------------------------------------------
# Pre-flight
#-----------------------------------------------------------
[ -f docker-compose.yml ] || { err "Run this from the project root."; exit 1; }

if ! command -v docker >/dev/null 2>&1; then
  err "docker is not installed."
  echo "    Install: https://docs.docker.com/engine/install/"
  exit 1
fi

if ! docker compose version >/dev/null 2>&1; then
  err "Docker Compose v2 is required."
  echo "    Install: apt install docker-compose-plugin   (or use Docker Desktop)"
  exit 1
fi

if ! docker info >/dev/null 2>&1; then
  err "Cannot reach the Docker daemon."
  echo "    Tip: add your user to the docker group:"
  echo "      sudo usermod -aG docker \$USER && newgrp docker"
  exit 1
fi

#-----------------------------------------------------------
# Helpers
#-----------------------------------------------------------
gen_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 64
  else
    head -c 64 /dev/urandom | xxd -p -c 256
  fi
}

read_default() {
  local prompt_text="$1" default="$2" varname="$3" answer
  prompt "$prompt_text [$default]: "
  read -r answer || true
  printf -v "$varname" '%s' "${answer:-$default}"
}

read_secret() {
  local prompt_text="$1" varname="$2" min_len="${3:-8}" answer
  while true; do
    prompt "$prompt_text (min $min_len chars): "
    stty -echo
    read -r answer || true
    stty echo
    echo
    if [ "${#answer}" -ge "$min_len" ]; then
      printf -v "$varname" '%s' "$answer"
      break
    fi
    err "too short — try again"
  done
}

#-----------------------------------------------------------
# .env
#-----------------------------------------------------------
if [ -f .env ]; then
  log "Existing .env detected — keeping it."
  warn "To regenerate: rm .env && re-run this script."
else
  echo
  log "First-time setup. We'll generate a JWT secret and ask for credentials."
  echo

  JWT_SECRET=$(gen_secret)
  read_default "Admin username"      "admin"   ADMIN_USERNAME
  read_secret  "Admin password"                ADMIN_PASSWORD 8
  read_default "SFTP username"       "ftpuser" SFTP_USERNAME
  read_secret  "SFTP password"                 SFTP_PASSWORD 6
  read_default "Public URL (used to build share links)" "https://localhost:8082" PUBLIC_URL
  read_default "Bind address (use 127.0.0.1 if behind reverse proxy)" "0.0.0.0" BIND_ADDR
  read_default "HTTPS port"          "8082"    HTTPS_PORT
  read_default "SFTP port"           "2222"    SFTP_PORT

  umask 077
  cat > .env <<EOF
# Generated by install.sh — keep this file private.
JWT_SECRET=${JWT_SECRET}

ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_PASSWORD=${ADMIN_PASSWORD}

SFTP_USERNAME=${SFTP_USERNAME}
SFTP_PASSWORD=${SFTP_PASSWORD}

PUBLIC_URL=${PUBLIC_URL}

BIND_ADDR=${BIND_ADDR}
HTTPS_PORT=${HTTPS_PORT}
SFTP_PORT=${SFTP_PORT}
EOF
  umask 022
  log ".env created (mode 600)."
fi

#-----------------------------------------------------------
# Data dirs + cert dir
#-----------------------------------------------------------
mkdir -p data/files data/db certs
log "data/ and certs/ directories ready."

if [ -f certs/fullchain.pem ] && [ -f certs/privkey.pem ]; then
  log "Found TLS cert in ./certs/ — will use it."
else
  warn "No TLS cert in ./certs/ — container will generate a self-signed cert on first run."
  warn "For production, replace with real cert files (fullchain.pem + privkey.pem) and restart."
fi

#-----------------------------------------------------------
# Build & run
#-----------------------------------------------------------
log "Building image (a few minutes on first run)…"
docker compose build

log "Starting container…"
docker compose up -d

# Give it a moment, then sanity-check
sleep 4
if ! docker compose ps | grep -q "Up"; then
  err "Container is not running. Logs follow:"
  docker compose logs --tail=40
  exit 1
fi

#-----------------------------------------------------------
# Done
#-----------------------------------------------------------
PUBLIC_URL_LINE=$(grep '^PUBLIC_URL=' .env | cut -d= -f2-)

echo
log "All set."
echo
echo "  Web UI : ${PUBLIC_URL_LINE}"
echo "  SFTP   : sftp -P $(grep '^SFTP_PORT=' .env | cut -d= -f2-) <user>@<host>"
echo
echo "  Logs       :  docker compose logs -f"
echo "  Stop       :  docker compose down"
echo "  Backup     :  ./scripts/backup.sh"
echo
warn "If you used a self-signed cert, your browser will warn the first time."
